=== yarul12GC/tituloxml/XSD/02-esquema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://www.siged.sep.gob.mx/titulos/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="TituloElectronico">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="FirmaResponsables">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="FirmaResponsable">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="nombre"/>
                      <xs:attribute type="xs:string" name="primerApellido"/>
                      <xs:attribute type="xs:string" name="segundoApellido"/>
                      <xs:attribute type="xs:string" name="curp"/>
                      <xs:attribute type="xs:byte" name="idCargo"/>
                      <xs:attribute type="xs:string" name="cargo"/>
                      <xs:attribute type="xs:string" name="abrTitulo"/>
                      <xs:attribute type="xs:string" name="sello"/>
                      <xs:attribute type="xs:string" name="certificadoResponsable"/>
                      <xs:attribute type="xs:long" name="noCertificadoResponsable"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Institucion">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:int" name="cveInstitucion"/>
                <xs:attribute type="xs:string" name="nombreInstitucion"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="Carrera">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:int" name="cveCarrera"/>
                <xs:attribute type="xs:string" name="nombreCarrera"/>
                <xs:attribute type="xs:date" name="fechaInicio"/>
                <xs:attribute type="xs:date" name="fechaTerminacion"/>
                <xs:attribute type="xs:byte" name="idAutorizacionReconocimiento"/>
                <xs:attribute type="xs:string" name="autorizacionReconocimiento"/>
                <xs:attribute type="xs:int" name="numeroRvoe"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="Profesionista">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="curp"/>
                <xs:attribute type="xs:string" name="nombre"/>
                <xs:attribute type="xs:string" name="primerApellido"/>
                <xs:attribute type="xs:string" name="segundoApellido"/>
                <xs:attribute type="xs:string" name="correoElectronico"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="Expedicion">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:date" name="fechaExpedicion"/>
                <xs:attribute type="xs:byte" name="idModalidadTitulacion"/>
                <xs:attribute type="xs:string" name="modalidadTitulacion"/>
                <xs:attribute type="xs:date" name="fechaExencionExamenProfesional"/>
                <xs:attribute type="xs:byte" name="cumplioServicioSocial"/>
                <xs:attribute type="xs:byte" name="idFundamentoLegalServicioSocial"/>
                <xs:attribute type="xs:string" name="fundamentoLegalServicioSocial"/>
                <xs:attribute type="xs:byte" name="idEntidadFederativa"/>
                <xs:attribute type="xs:string" name="entidadFederativa"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="Antecedente">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="institucionProcedencia"/>
                <xs:attribute type="xs:byte" name="idTipoEstudioAntecedente"/>
                <xs:attribute type="xs:string" name="tipoEstudioAntecedente"/>
                <xs:attribute type="xs:byte" name="idEntidadFederativa"/>
                <xs:attribute type="xs:string" name="entidadFederativa"/>
                <xs:attribute type="xs:date" name="fechaTerminacion"/>
                <xs:attribute type="xs:int" name="noCedula"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:float" name="version"/>
      <xs:attribute type="xs:int" name="folioControl"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== yarul12GC/tituloxml/XSD/02-ejemplo-basico.xml
<TituloElectronico xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.siged.sep.gob.mx/titulos/" xsi:noNamespaceschemaLocation="02-esquema.xsd" version="1.0" folioControl="15010037">
<FirmaResponsables>
<FirmaResponsable nombre="IZCOATL JAFET" primerApellido="ARRIAGA" segundoApellido="LOPEZ" curp="AILI720420HMCRPZ06" idCargo="1" cargo="DIRECTOR" abrTitulo="LIC." sello="HbvHJSbBhE/IlK0CXEaTQqBlHsMpCY6dKGW2JHFl2FNTSke5Vb8gA1/Xma44mn06GdfTigaDkCCIGbMKkroLp/3M855aQCE1Ggr2RCOQd9KY0fAZkUHun4Oj+MXPbHuy7NfEDDJH2Lg30XX9irHI+TS9WTp0crJZj9iLfisY2d0lqPIn1Rdc9inFFnod7l0G3YjiNkz4X2Emmhfeu/26MgnA+adhYa98uFbEU6sawVRrRmij/rkKAYwFywWFNCUtqMrBhETo6NEb1g3Kg16ecOFA2dhimQAjUSvnKJ+23eOmp7NiE80eQZFJFveJtBvOG7YD+gPMc9fh61q6K6RLrQ==" certificadoResponsable="MIIGbzCCBFegAwIBAgIUMDAwMDEwMDAwMDA0MTQwNjQ0ODIwDQYJKoZIhvcNAQELBQAwggGyMTgwNgYDVQQDDC9BLkMuIGRlbCBTZXJ2aWNpbyBkZSBBZG1pbmlzdHJhY2nDs24gVHJpYnV0YXJpYTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMR8wHQYJKoZIhvcNAQkBFhBhY29kc0BzYXQuZ29iLm14MSYwJAYDVQQJDB1Bdi4gSGlkYWxnbyA3NywgQ29sLiBHdWVycmVybzEOMAwGA1UEEQwFMDYzMDAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBEaXN0cml0byBGZWRlcmFsMRQwEgYDVQQHDAtDdWF1aHTDqW1vYzEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMV0wWwYJKoZIhvcNAQkCDE5SZXNwb25zYWJsZTogQWRtaW5pc3RyYWNpw7NuIENlbnRyYWwgZGUgU2VydmljaW9zIFRyaWJ1dGFyaW9zIGFsIENvbnRyaWJ1eWVudGUwHhcNMTkwMzI3MTg1NDI2WhcNMjMwMzI3MTg1NTA2WjCB3TEkMCIGA1UEAxMbSVpDT0FUTCBKQUZFVCBBUlJJQUdBIExPUEVaMSQwIgYDVQQpExtJWkNPQVRMIEpBRkVUIEFSUklBR0EgTE9QRVoxJDAiBgNVBAoTG0laQ09BVEwgSkFGRVQgQVJSSUFHQSBMT1BFWjELMAkGA1UEBhMCTVgxJzAlBgkqhkiG9w0BCQEWGGphZmV0X2xhd3llckBob3RtYWlsLmNvbTEWMBQGA1UELRMNQUlMSTcyMDQyMEpDNjEbMBkGA1UEBRMSQUlMSTcyMDQyMEhNQ1JQWjA2MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiBYTbdUkjmLaJxGhXulFpE2l4dP3PB5SdJpsPiA+IiGB/wLakPrrFb2ElQ+UZPZDpGIW8ehydDK4rHoitV+6/M1Dmz5Ayk4g0y869AVxhRQ9yDKZFQtiDcsx/KP9Xw6zIaAPoXadPHx027U7GFGj6hPUIHEjez4kWlVghx9lwXCE6ode6FudcXOvSI4Tha4duRHTZS2wd5TKQfC0P3av4pRNbaF8ezlt81nbcZPUuiJIycNteVXLO4vV8qnwh/R39G9jzCyFf/o8uVhIm1AEP3Tinp10s6kyvQ4jdZYGarI+I2xUj6Ogpw2zTdwARcui57K9tkcZ+wupG2f5trUYFwIDAQABo08wTTAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwID2DARBglghkgBhvhCAQEEBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwQGCCsGAQUFBwMCMA0GCSqGSIb3DQEBCwUAA4ICAQB7OuuiIRqGFHVbtctwC580GluaQSphRTFzI5a5vRMiQukF3eDdtmql+8kyCaL3rrFICGNHiskoLUW93fIp6nKgPn9rScQXZ2ISQZoxYLMVIjJURkUSRHHHc9LUCreYwZ4RR26K/D2LfKujNRV9UBndJmVoPmfds8nJErsMe0TKb+ap7WQSwbiQj9q28YzkWJdfSOjzd0MeJ399EVXENSoOMiqPydF7ZtdrItHnO7CGEvabozMBEqwLWu5eQXbEyN8h6nY/vNydzMMTKAI9C530m7Uhp4cUgTaAzSu2DzWIgKP3ikvoA7peXrkMGaQUyAK3SkgSJyukMwGyupWjU11yD+mu5F94fbugyp7tYF8AR7kUyOVkKBuK2gxEO9GMe4v0osuWwZp5GII7G2QkWH50LOn5mBKGbDBdaonMhzaaNztkfZlNwRvq/ffvu9/8jaz5jtHwY8aQDGts1qyvWeJIaGgQZZgylLfria2zTqSZYhNAG+xjqu8tBHvrPgkDtD9sF6qz5nHp8RY+RQHbI7AcAt8zXeClwp6j/HbbFQ53iclHI4kiaPBHu6lhD0hFym/potLFhuLx2QX/rRJcCAknwuxWppX4fuYJbCyijcR3aqoaw2yz870M+3khkMS8j8/Pb2B2DRRfvsedNCPTTQc2UMuChcfErzr5U1qqpTSidw==" noCertificadoResponsable="00001000000414064482"/>
</FirmaResponsables>
<Institucion cveInstitucion="150852" nombreInstitucion="UNIVERSIDAD ALFA LAMBDA"/>
<Carrera cveCarrera="612627" nombreCarrera="DOCTORADO EN DERECHO PROCESAL" fechaInicio="2014-09-22" fechaTerminacion="2016-08-26" idAutorizacionReconocimiento="1" autorizacionReconocimiento="RVOE FEDERAL" numeroRvoe="20150379"/>
<Profesionista curp="AEVR590101HMCRLL04" nombre="RAUL HORACIO" primerApellido="ARENAS" segundoApellido="VALDES" correoElectronico="ualarchivo.edu@gmail.com"/>
<Expedicion fechaExpedicion="2022-02-28" idModalidadTitulacion="2" modalidadTitulacion="POR PROMEDIO" fechaExencionExamenProfesional="2022-02-25" cumplioServicioSocial="0" idFundamentoLegalServicioSocial="5" fundamentoLegalServicioSocial="NO APLICA" idEntidadFederativa="15" entidadFederativa="MÉXICO"/>
<Antecedente institucionProcedencia="UNIVERSIDAD AUTONOMA DEL ESTADO DE MEXICO FACULTAD DE DERECHO, DEPENDIENTE DE ESTA INSTITUCION" idTipoEstudioAntecedente="1" tipoEstudioAntecedente="MAESTRÍA" idEntidadFederativa="15" entidadFederativa="MÉXICO" fechaTerminacion="2003-02-12" noCedula="4238032"/>
</TituloElectronico>
